export interface SiteContentSettings {
  brandName: string;
  logoMode: "text" | "image";
  logoText: string;
  logoImageUrl?: string;
  logoAltText?: string;
  navbarLinkProducts: string;
  navbarLinkAbout: string;
  navbarLinkContact: string;
  navbarCtaLabel: string;
  heroSubtitle: string;
  heroTitleLine1: string;
  heroTitleLine2: string;
  heroTitleLine3: string;
  heroDescription: string;
  heroPrimaryButtonLabel: string;
  heroSecondaryButtonLabel: string;
  heroBadgeValue: string;
  heroBadgeLabel: string;
  heroImageUrl?: string;
  heroImageAlt?: string;
  stripBannerItem1: string;
  stripBannerItem2: string;
  stripBannerItem3: string;
  stripBannerItem4: string;
  featuredProductsTitle: string;
  featuredProductsViewAllLabel: string;
  aboutSubtitle: string;
  aboutTitleLine1: string;
  aboutTitleLine2: string;
  aboutDescription: string;
  aboutButtonLabel: string;
  aboutImageUrl?: string;
  aboutImageAlt?: string;
  feature1Title: string;
  feature1Text: string;
  feature2Title: string;
  feature2Text: string;
  feature3Title: string;
  feature3Text: string;
  ctaTitleLine1: string;
  ctaTitleLine2: string;
  ctaDescription: string;
  ctaButtonLabel: string;
  footerCopyrightText: string;
}

export type SiteContentInput = SiteContentSettings;

export interface SiteContentLocaleInput {
  locale: string;
  navbarLinkProducts: string;
  navbarLinkAbout: string;
  navbarLinkContact: string;
  navbarCtaLabel: string;
  heroSubtitle: string;
  heroTitleLine1: string;
  heroTitleLine2: string;
  heroTitleLine3: string;
  heroDescription: string;
  heroPrimaryButtonLabel: string;
  heroSecondaryButtonLabel: string;
  heroBadgeValue: string;
  heroBadgeLabel: string;
  stripBannerItem1: string;
  stripBannerItem2: string;
  stripBannerItem3: string;
  stripBannerItem4: string;
  featuredProductsTitle: string;
  featuredProductsViewAllLabel: string;
  aboutSubtitle: string;
  aboutTitleLine1: string;
  aboutTitleLine2: string;
  aboutDescription: string;
  aboutButtonLabel: string;
  feature1Title: string;
  feature1Text: string;
  feature2Title: string;
  feature2Text: string;
  feature3Title: string;
  feature3Text: string;
  ctaTitleLine1: string;
  ctaTitleLine2: string;
  ctaDescription: string;
  ctaButtonLabel: string;
  footerCopyrightText: string;
}
